<select  name="ccounty" required>
			<option selected>Select your county</option>
			<option value="Baringo">Baringo County</option>
			<option value="Bomet">Bomet County</option>
			<option value="Bungoma">Bungoma County</option>
			<option value="Busia">Busia County</option>
			<option value="ElgeyoMarakwet">Elgeyo Marakwet County</option>
			<option value="Embu">Embu County</option>
			<option value="Garissa">Garissa County</option>
			<option value="HomaBay">Homa Bay County</option>
			<option value="Isiolo">Isiolo County</option>
			<option value="Kajiado">Kajiado County</option>
			<option value="Kakamega">Kakamega County</option>
			<option value="Kericho">Kericho County</option>
			<option value="Kiambu">Kiambu County</option>
			<option value="Kilifi">Kilifi County</option>
			<option value="Kirinyaga">Kirinyaga County</option>
			<option value="Kisii">Kisii County</option>
			<option value="Kisumu">Kisumu County</option>
			<option value="Kitui">Kitui County</option>
			<option value="Kwale">Kwale County</option>
			<option value="Laikipia">Laikipia County</option>
			<option value="Lamu">Lamu County</option>
			<option value="Machakos">Machakos County</option>
			<option value="Makueni">Makueni County</option>
			<option value="Mandera">Mandera County</option>
			<option value="Meru">Meru County</option>
			<option value="Migori">Migori County</option>
			<option value="Marsabit">Marsabit County</option>
			<option value="Mombasa">Mombasa County</option>
			<option value="Muranga">Muranga County</option>
			<option value="Nairobi">Nairobi County</option>
			<option value="Nakuru">Nakuru County</option>
			<option value="Nandi">Nandi County</option>
			<option value="Narok">Narok County</option>
			<option value="Nyamira">Nyamira County</option>
			<option value="Nyandarua">Nyandarua County</option>
			<option value="Nyeri">Nyeri County</option>
			<option value="Samburu">Samburu County</option>
			<option value="Siaya">Siaya County</option>
			<option value="TaitaTaveta">Taita Taveta County</option>
			<option value="TanaRiver">Tana River County</option>
			<option value="TharakaNithi">Tharaka Nithi County</option>
			<option value="TransNzoia">Trans Nzoia County</option>
			<option value="Turkana">Turkana County</option>
			<option value="UasinGishu">Uasin Gishu County</option>
			<option value="Vihiga">Vihiga County</option>
			<option value="Wajir">Wajir County</option>
			<option value="WestPokot">West Pokot County</option>
		</select>